language: node_js

node_js:
 - "0.10"
 - "0.8"

before_install:
 - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
 - sudo apt-get update -y

install:
 - sudo apt-get install -y libgeos-dev

before_script:
 - npm install

script:
 - npm test
